### ISSUE TITLE
Boundary conditions problem of minhash.

### ISSUE THREAD

**Issue by yangzhou04** [tdebatty/java-LSH#1]
I'm not sure whether It is reasonalbe, but Please try this test case:

``` java
boolean[] set1 = new boolean[5];
set1[0] = false;
set1[1] = false;
set1[2] = false;
set1[3] = false;
set1[4] = false;
int[] sig1 = minhash.hash(set1);
minhash.printSignature(sig1);


TreeSet<Integer> set2 = new TreeSet<Integer>();
set2.add(0);
int[] sig2 = minhash.hash(set2);
minhash.printSignature(sig2);

System.out.println(minhash.similarity(sig1, sig2));
```

sig1 will be all Integer.MAX and the result similarity will be 0.

---

Oh, i see what's going on immediately after the post.  the sim =  a / (a+b+c)  instead of (a+d) / (a+b+c+d)

**Comment by tdebatty** [comment]
Hello,

The result seems correct. In your test case:
Set1={} (the set is empty)
Set2={0}

MinHash computes an approximation of Jaccard index:
|Set1 intersection Set2| / |Set1 union Set2| = 0/1
