### ISSUE TITLE
avoid java serialization

### ISSUE THREAD

**Issue by kireet** [tdebatty/java-LSH#10]
java serialization can be quite tricky to get right, especially as code changes over time. It would be nice if client code had the option of passing a seed value to the LSH classes that would be passed through to `Random` objects created during initialization and thus allowing for consistent hashes across object instantiations without having to deal with serialization at all.

**Comment by tdebatty** [comment]
Hi,
Sorry for the late answer... I really like your idea. I'm gonna give it a try this week!
Best regards,

**Comment by kireet** [comment]
i took a shot at this and created a pull request in issue #11 

sorry, i am not that familiar with github so i didn't know how to attach it to this issue...

**Comment by tdebatty** [comment]
Hi,
I merged you pull request
I made some style modifications to be consistent with the rest of the code
and I made a new release (should be available on maven within a few hours)
I will also modify the examples to mention this possibility
Best regards,
