### ISSUE TITLE
Another similarity measure

### ISSUE THREAD

**Issue by mohamadian** [tdebatty/java-LSH#17]
Hello, 
Thank you for your grate library. I have a question. How can I change the similarity measure? I want to use Euclidean distance instead of Cosine similarity, how can I do it? I mean does it possible to change your code and use another similarity measure instead of Cosine similarity?

Thank you in advance

**Comment by tdebatty** [comment]
Hi,
Thank you for your interest! LSH functions do exist for Euclidean distance,
but I currently have no time to make an implementation...

Le dim. 26 nov. 2017 à 14:13, Mahdi Mohamadian <notifications@github.com> a
écrit :
