### ISSUE TITLE
Understanding LSH.hashSignature Implementation

### ISSUE THREAD

**Issue by sarda014** [tdebatty/java-LSH#19]
Hello Thibault,

Thank you for the great project, I am using the LSHSuperBit class for some experimentation to find similar items.

I am not able to understand the logic `LSH.hashSignature(final boolean[] signature)` method uses to group similar items into same bucket.

Can you please point me to some resource which you used to implement this? Thank you.

**Comment by tdebatty** [comment]
Dear,

Thank you for your interest!

The implementation is based on the book Leskovec, Rajaraman & Ullman (2014), "Mining of Massive Datasets", Cambridge University Press.

https://github.com/tdebatty/java-LSH/blob/a4194adf6600787dca6f07b94f33f6c4787ffda0/src/main/java/info/debatty/java/lsh/LSH.java#L6

Best regards,
