### ISSUE TITLE
Missing utils classes

### ISSUE THREAD

**Issue by atifuw** [tdebatty/java-LSH#23]
GRADLE: info.debatty:java-lsh:0.11

The class info.debatty.java.lsh.SuperBit has a dependency on the following classes from the "info.debatty.java.utils" package.  However, these classes are not in the source code base.

- info.debatty.java.utils.SparseDoubleVector;
- info.debatty.java.utils.SparseIntegerVector;

**Comment by tdebatty** [comment]
Fixed in v0.12
