### ISSUE TITLE
I get different hash values on the same vector when I run LSH multiple times.

### ISSUE THREAD

**Issue by radikaka** [tdebatty/java-LSH#3]
I get different hash values on the same vector when I run LSH multiple times.

**Comment by tdebatty** [comment]
Hello,

This is normal: when you use LSH, the coefficients of the hashing functions are choosen randomly.
So if you run your program multiple times, the hashes will be different at each run.

What you have to do is serialize and save your LSH object between runs. In this way:
- same input vectors will allways produce the same hashes
- hashes from different vectors can be used to compute the approximative similarity...

Hope this is clear? I will add an example in the code...

Best regards,

Thibault

**Comment by tdebatty** [comment]
Hello,
Just added an example to illustrate this:
https://github.com/tdebatty/java-LSH/blob/master/src/main/java/info/debatty/java/lsh/examples/SerializeExample.java

Don't forget to update your dependency to the last version (0.8)

Thibault

**Comment by radikaka** [comment]
That makes sense,Thanks a lot:-)
I will update and try to serialize my lsh object.

_Regards,_
_Lakshmi Kasinathan https://www.linkedin.com/in/lkasinathan_
_MS in Computer Science_
_Viterbi School of Engineering, USC._
_+1 (213) 399-1006_

**Comment by radikaka** [comment]
I ran the serialization example as is.
Only change I made was use a LSHSuperBit instead of a LSHMinHash object.
After reading back the serialize object from the file, I don't get the same object back - there is a change in the no of stages!

Here's the OP when I run the serialization example. Any pointers?

[6 0 ]
[1 9 ]
LSH object serialized to /tmp/lshobject8257640076697625203.ser
[8 8 0 ]

**Comment by tdebatty** [comment]
Hello,

This is strange indeed!
Could you send me the source code of your test? (or attach it to the issue)?

Best regards,

**Comment by radikaka** [comment]
I just realised my mistake - I didn't update my sources!
Once I moved to version 0.8, it worked like a charm:-)

**Comment by tdebatty** [comment]
:-) OK

Don't hesitate to contact me if you have other questions!

Best regards,

Thibault
