### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by ogreyesp** [tdebatty/java-LSH#7]
Hello,

Could you provide the code of info.debatty.java.utils.SparseDoubleVector and info.debatty.java.utils.SparseIntegerVector. I have downloaded the project, but these two files are not included in the zip file.

Best regards.

Oscar

**Comment by tdebatty** [comment]
Hello,

Those classes are currently part of the java-string-similarity package:
https://github.com/tdebatty/java-string-similarity

https://github.com/tdebatty/java-string-similarity/tree/master/src/main/java/info/debatty/java/utils

Best regards,
