### ISSUE TITLE
Negative bucket index

### ISSUE THREAD

**Issue by kumaramit01** [tdebatty/java-LSH#9]
When I run the SimpleLSHMinHashExample with a large size of the vector say n = 100000 -I end up getting negative bucket:

Errors with  

> java -Xmx16G -classpath java-string-similarity-0.13.jar:java-lsh-0.8.jar:. SimpleLSHMinHashExample
> Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -4
>     at SimpleLSHMinHashExample.main(SimpleLSHMinHashExample.java:48)

**Comment by tdebatty** [comment]
Hi,

Thank you for reporting this bug. I will fix it and publish a new release as soon as possible!

**Comment by tdebatty** [comment]
Fixed in release 0.9
